### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by westhecool** [crunchy-labs/enhance-crunchyroll#1]
Whenever I click on the download button it just shows the error "TypeError: Cannot read properties of undefined" on the chrome extension.

**Comment by MommyNearest** [comment]
I have the same issue, although mine says "TypeError: Cannot read properties of undefined (reading '')"

For whatever reason it includes that additional (reading '') bit.

**Comment by bytedream** [comment]
Crunchyroll disabled the endpoint which I used to download videos. Luckily a old one is still working, so the extension is using it instead. Updates are available in the newest version
