### ISSUE TITLE
Feature Request: Labeling Filler Episodes

### ISSUE THREAD

**Issue by nachikamod** [crunchy-labs/enhance-crunchyroll#3]
I am thinking about starting One Piece. Watching 1000+ episodes will be a pain. If the extension can help with filtering filler episodes or at least labeling them, would be a nice feature.

**Comment by bytedream** [comment]
This is a too specific case, so I won't add it. But there are plenty of websites which are listing the filler episodes so manually checking shouldn't be that hard
